# Conda environment specification. Details about the Conda environment file format:
# https://conda.io/docs/user-guide/tasks/manage-environments.html#create-env-file-manually

name: training_env
dependencies:
  - python=3.7.10
  - scikit-learn=0.23.2
  - pandas=1.1.5
  - fastai
  - matplotlib=3.3.3
  - pip:
    - torchvision
    - torch
    - azureml-defaults==1.19.0
    - beautifulsoup4
    - azure-storage-blob
    - requests
    - click==7.1.2
    - mlflow
channels:
  - conda-forge
  - fastchan