name: 'Training'

on:
  push:
    branches:
    - main
  pull_request:

jobs:   
  train:
      runs-on: ubuntu-latest
      steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check Out Repository
        id: checkout_repository
        uses: actions/checkout@v2